# homework for httpd and apache2
---
- hosts: node04 node03
  become: true
  vars: 
    http_port: 8080
  tasks:
  - name: Install httpd on RedHat
    yum: name=httpd  state=present
    when: ansible_os_family == "RedHat"
  - name: Install apache2 on Ubuntu
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian"
  - name: start the service RedHat
    service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"
